/*
 * FrmMenu.java creada el 20/02/2023.
 */
package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;
import dominio.Usuario;
import interfaces.ICuentasDAO;
import interfaces.ITransaccionesDAO;
import javax.swing.JOptionPane;

/**
 * Este frame se utiliza para acceder al menú de operaciones.
 *
 * @author 00000233259 y 00000233410.
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Este atributo se utiliza para llevar un registro cronológicamente de los
     * datos.
     */
    private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    /**
     * Este atributo representa la DAO de Clientes.
     */
    public final IClientesDAO clientesDAO;
    /**
     * Este atributo representa la DAO de Direcciones.
     */
    public final IDireccionesDAO direccionesDAO;
    /**
     * Este atributo representa la DAO de Transacciones.
     */
    public final ITransaccionesDAO transaccionesDAO;
    /**
     * Este atributo representa la DAO de Cuentas.
     */
    public final ICuentasDAO cuentasDAO;
    /**
     * Este atributo representa el usuario logeado actualmente.
     */
    private Usuario usuarioLogeado;

    /**
     * Método constructor que inicializa los atributos al valor de sus
     * parámetros.
     *
     * @param clientesDAO representa la DAO de Clientes.
     * @param direccionesDAO representa la DAO de Direcciones.
     * @param transaccionesDAO representa la DAO de Transacciones.
     * @param cuentasDAO representa la DAO de Cuentas.
     * @param usuarioLogeado representa el usuario actual.
     */
    public FrmMenu(IClientesDAO clientesDAO, IDireccionesDAO direccionesDAO, ITransaccionesDAO transaccionesDAO, ICuentasDAO cuentasDAO, Usuario usuarioLogeado) {
        this.clientesDAO = clientesDAO;
        this.direccionesDAO = direccionesDAO;
        this.transaccionesDAO = transaccionesDAO;
        this.cuentasDAO = cuentasDAO;
        this.usuarioLogeado = usuarioLogeado;
        initComponents();
        lblNombre.setText(usuarioLogeado.getCliente().getNombre());
        lblApellido.setText(usuarioLogeado.getCliente().getApellidoPaterno() + "!");
        this.setSize(450, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnVerRetiros = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        btnCancelarCuenta1 = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();
        btnVerTransacciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAyuda.setBackground(new java.awt.Color(183, 210, 242));
        btnAyuda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        btnTransferir.setBackground(new java.awt.Color(65, 103, 158));
        btnTransferir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));

        btnRetirar.setBackground(new java.awt.Color(65, 103, 158));
        btnRetirar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        btnModificarDatos.setBackground(new java.awt.Color(65, 103, 158));
        btnModificarDatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarDatos.setText("Modificar datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, -1));

        btnVerRetiros.setBackground(new java.awt.Color(65, 103, 158));
        btnVerRetiros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerRetiros.setForeground(new java.awt.Color(255, 255, 255));
        btnVerRetiros.setText("Ver retiros");
        btnVerRetiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRetirosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerRetiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, -1));

        btnCrearCuenta.setBackground(new java.awt.Color(65, 103, 158));
        btnCrearCuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, -1));

        btnCancelarCuenta1.setBackground(new java.awt.Color(65, 103, 158));
        btnCancelarCuenta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelarCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCuenta1.setText("Cancelar cuenta");
        btnCancelarCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, -1));

        btnDesconectar.setBackground(new java.awt.Color(183, 210, 242));
        btnDesconectar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 103, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellido.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 40));

        lblNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 40));

        lblBienvenido.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("¡Bienvenido de nuevo");
        jPanel2.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, 110));

        lblMenu1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblMenu1.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu1.setText("Menú");
        jPanel1.add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnVerTransacciones.setBackground(new java.awt.Color(65, 103, 158));
        btnVerTransacciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerTransacciones.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTransacciones.setText("Ver transacciones");
        btnVerTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTransaccionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para realizar transferencias.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        FrmTransferencia frmTransferencia = new FrmTransferencia(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmTransferencia.setVisible(true);
    }//GEN-LAST:event_btnTransferirActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame cancelar cuentas.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnCancelarCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCuenta1ActionPerformed
        FrmCancelarCuenta frmCancelarCuenta = new FrmCancelarCuenta(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmCancelarCuenta.setVisible(true);
    }//GEN-LAST:event_btnCancelarCuenta1ActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para modificar datos.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        FrmModificarDatos frmModificarDatos = new FrmModificarDatos(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmModificarDatos.setVisible(true);
    }//GEN-LAST:event_btnModificarDatosActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para ver retiros.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnVerRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRetirosActionPerformed
        FrmVerRetiros frmVerRetiros = new FrmVerRetiros(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmVerRetiros.setVisible(true);
    }//GEN-LAST:event_btnVerRetirosActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para crear cuentas.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        FrmCrearCuenta frmCrearCuenta = new FrmCrearCuenta(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmCrearCuenta.setVisible(true);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para generar retiros.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        FrmRetirar frmRetirar = new FrmRetirar(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmRetirar.setVisible(true);
    }//GEN-LAST:event_btnRetirarActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame login.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        FrmLogin frmLogin = new FrmLogin(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO);
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnDesconectarActionPerformed
    /**
     * Este evento ocurre cuando un usuario da un click en el botón y se abre el
     * frame para ver transacciones.
     *
     * @param evt Evento al dar click en el botón.
     */
    private void btnVerTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTransaccionesActionPerformed
        FrmVerOperaciones frmVerOperaciones = new FrmVerOperaciones(clientesDAO, direccionesDAO, transaccionesDAO, cuentasDAO, usuarioLogeado);
        this.setVisible(false);
        frmVerOperaciones.setVisible(true);
    }//GEN-LAST:event_btnVerTransaccionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCancelarCuenta1;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVerRetiros;
    private javax.swing.JButton btnVerTransacciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
